version: "3"
services:
  project:
    network_mode: host

    image: ydb-test/go-pqlib
    build:
      context: ../../..
      dockerfile: languages/go/libpq/Dockerfile
      network: host
    environment:
      - PGUSER=${YDB_PG_USER:-postgres}
      - PGPASSWORD=${YDB_PG_PASSWORD:-password}
      - PGHOST=${YDB_PG_HOST:-ydb}
      - PGPORT=${YDB_PG_PORT:-5432}
      - PGDATABASE=${YDB_PG_DATABASE:-/local}
      - PQGOSSLTESTS=0
      - PQSSLCERTTEST_PATH=certs
      - YDB_PG_TESTNAME=${YDB_PG_TESTNAME:-}
    volumes:
      - ./exchange:/exchange
      - ./test-result/:/test-result
