version: "3"
services:
  ydb:
    image: cr.yandex/yc/yandex-docker-local-ydb:trunk
    environment:
      - "YDB_DEFAULT_LOG_LEVEL=DEBUG"
      - "GRPC_TLS_PORT=2135"
      - "GRPC_PORT=2136"
      - "MON_PORT=8765"
      - "YDB_USE_IN_MEMORY_PDISKS=true"
      - "POSTGRES_PASSWORD=password"
    healthcheck:
      test: "/bin/sh /health_check"
      interval: 1s
      start_period: 1m
  go-libpq:
    depends_on:
      ydb:
        condition: service_healthy
    image: ydb-test/go-pqlib
    build:
      context: .
    environment:
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGHOST=ydb
      - PGPORT=5432
      - PQGOSSLTESTS=0
      - PQSSLCERTTEST_PATH=certs
    volumes:
      - ./project-sources:/sources
      - ../../../tmp/test-result/go-libpq:/test-result
