version: "3"
services:
  project:
    network_mode: host
    image: ydb-test/psycopg2
    environment:
      - PSYCOPG2_TESTDB=${YDB_PG_DATABASE:-/local}
      - PSYCOPG2_TESTDB_HOST=${YDB_PG_HOST:-ydb}
      - PSYCOPG2_TESTDB_PORT=${YDB_PG_PORT:-5432}
      - PSYCOPG2_TESTDB_USER=${YDB_PG_USER:-postgres}
      - PSYCOPG2_TESTDB_PASSWORD=${YDB_PG_PASSWORD:-password}
      - YDB_PG_TESTNAME=${YDB_PG_TESTNAME:-}
    build:
      context: .
      network: host
    volumes:
      - ./exchange:/exchange
      - ./test-result/:/test-result
