convert:
  change_error_to_failure: True

tickets:
  - name:  KIKIMR-17960 # CREATE TEMP TABLE
    tests:
      golang-lib-pq:
        - TestBindError
        - TestCommit
        - TestCopyFromError
        - TestCopyInBinaryError
        - TestErrorDuringStartupClosesConn
        - TestCommit
        - TestCopyFromError
        - TestCopyInBinaryError
        - TestCopyInMultipleValues
        - TestCopyInStmtAffectedRows
        - TestCopyInTypes
        - TestCopyInWrongType
        - TestCopyRespLoopConnectionError
        - TestErrorOnExec
        - TestErrorOnQuery
        - TestErrorOnQueryRowSimpleQuery
        - TestExec
        - TestIssue494
        - TestQueryRowBugWorkaround
        - TestReturning
        - TestRowsResultTag
        - TestCopyInRaiseStmtTrigger
      python-psycopg2:
        - tests.test_transaction.TransactionTests.test_commit
        - tests.test_transaction.TransactionTests.test_failed_commit
        - tests.test_transaction.TransactionTests.test_rollback
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.testDictConnCursorArgs
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.testDictCursorWithNamedCursorFetchAll
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.testDictCursorWithNamedCursorFetchMany
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.testDictCursorWithNamedCursorFetchManyNoarg
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.testDictCursorWithNamedCursorFetchOne
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.testDictCursorWithNamedCursorIter
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.testDictCursorWithNamedCursorIterRowNumber
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.testDictCursorWithNamedCursorNotGreedy
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.testDictCursorWithPlainCursorFetchAll
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.testDictCursorWithPlainCursorFetchMany
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.testDictCursorWithPlainCursorFetchManyNoarg
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.testDictCursorWithPlainCursorFetchOne
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.testDictCursorWithPlainCursorIter
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.testDictCursorWithPlainCursorIterRowNumber
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.testPickleDictRow
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.testUpdateRow
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.test_copy
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.test_iter_methods
        - tests.test_extras_dictcursor.ExtrasDictCursorTests.test_order

  - name: KIKIMR-18080 # Parameter types
    tests:
      golang-lib-pq:
        - TestArrayValueBackend

  - name: KIKIMR-18115 # PG error format
    tests:
      golang-lib-pq:
        - TestBinaryByteSliceToInt
        - TestBinaryByteSlicetoUUID
        - TestErrorClass

  - name: KIKIMR-18122 # PG error codes and text
    tests:
      golang-lib-pq:
        - TestCopySyntaxError

  - name: KIKIMR-18049 # Pg Auth error
    tests:
      golang-lib-pq:
        - TestErrorDuringStartup

  - name: KIKIMR-18050 # Pg exnexisted table error
    tests:
      golang-lib-pq:
        - TestIssue617

  - name: KIKIMR-18116 # Prepare description. expected syntax error, got pq: got 1 parameters but the statement requires 0
    tests:
      golang-lib-pq:
        - TestByteSliceToText
        - TestDecodeUUIDBackend
        - TestEmptyResultSetColumns
        - TestEncodeAndParseTs
        - TestEncodeDecode
        - TestFormatTsBackend
        - TestInfinityTimestamp
        - TestIssue186
        - TestIssue196
        - TestParseErrorInExtendedQuery
        - TestReconnect
        - TestRuntimeParameters
        - TestStringToBytea
        - TestStringToUUID
        - TestTextByteSliceToInt
        - TestTextByteSliceToUUID
        - TestTimeWithTimezone
        - TestTimeWithTimezone/11:59:59+00:00_=>_0000-01-01T11:59:59Z
        - TestTimeWithTimezone/11:59:59+04:00_=>_0000-01-01T11:59:59+04:00
        - TestTimeWithTimezone/11:59:59+04:01:02_=>_0000-01-01T11:59:59+04:01
        - TestTimeWithTimezone/11:59:59-04:01:02_=>_0000-01-01T11:59:59-04:01
        - TestTimeWithTimezone/24:00+00_=>_0000-01-02T00:00:00Z
        - TestTimeWithTimezone/24:00Z_=>_0000-01-02T00:00:00Z
        - TestTimeWithTimezone/24:00-04:00_=>_0000-01-02T00:00:00-04:00
        - TestTimeWithTimezone/24:00:00+00_=>_0000-01-02T00:00:00Z
        - TestTimeWithTimezone/24:00:00.0+00_=>_0000-01-02T00:00:00Z
        - TestTimeWithTimezone/24:00:00.000000+00_=>_0000-01-02T00:00:00Z
        - TestTimeWithoutTimezone
        - TestTimeWithoutTimezone/11:59:59_=>_0000-01-01T11:59:59Z
        - TestTimeWithoutTimezone/24:00_=>_0000-01-02T00:00:00Z
        - TestTimeWithoutTimezone/24:00:00_=>_0000-01-02T00:00:00Z
        - TestTimeWithoutTimezone/24:00:00.0_=>_0000-01-02T00:00:00Z
        - TestTimeWithoutTimezone/24:00:00.000000_=>_0000-01-02T00:00:00Z
        - TestTimestampWithOutTimezone

  - name: KIKIMR-18184  # Prepared queries
    tests:
      golang-lib-pq:
        - TestStatment

  - name: KIKIMR-18118 # Fail transaction on error
    tests:
      golang-lib-pq:
        - TestCommitInFailedTransaction
        - TestCommitInFailedTransactionWithCancelContext

  - name: KIKIMR-18119 # LISTEN Queries, alternative is not implemented yet : 267
    tests:
      golang-lib-pq:
        - TestConnListen
        - TestConnUnlisten
        - TestConnUnlistenAll
        - TestListenerFailedQuery
        - TestListenerListen
        - TestListenerReconnect
        - TestListenerUnlisten
        - TestListenerUnlistenAll
        - TestNotifyExtra

  - name: KIKIMR-18060 # SSL Response
    tests:
      golang-lib-pq:
        - TestConnectorWithNoticeHandler_Simple
        - TestConnectorWithNotificationHandler_Simple
        - TestNewConnector_Connect
        - TestNewConnector_Driver
        - TestNewConnector_WorksWithOpenDB

  - name: KIKIMR-18120 # implicit cast params (pg_sleep)
    tests:
      golang-lib-pq:
        - TestContextCancelBegin
        - TestContextCancelExec
        - TestContextCancelQuery
        - TestIssue1046
        - TestStmtExecContext
        - TestStmtExecContext/context.Background
        - TestStmtExecContext/context.WithTimeout_exceeded
        - TestStmtExecContext/context.WithTimeout
        - TestStmtQueryContext
        - TestStmtQueryContext/context.Background
        - TestStmtQueryContext/context.WithTimeout_exceeded
        - TestStmtQueryContext/context.WithTimeout

  - name: KIKIMR-18178 # SELECT USER. alternative is not implemented yet : 142
    tests:
      golang-lib-pq:
        - TestPgpass

  - name: KIKIMR-18125 # SET LOCAL search_path
    tests:
      golang-lib-pq:
        - TestIssue282

  - name: KIKIMR-18174 # SET time zone
    tests:
      golang-lib-pq:
        - TestMultipleSimpleQuery
        - TestTimestampWithTimeZone

  - name: KIKIMR-18059 # Multiply results
    tests:
      golang-lib-pq:
        - TestMultipleEmptyResult

  - name: KIKIMR-18147 # Information schema
    tests:
      golang-lib-pq:
        - TestMultipleResult

  - name: KIKIMR-18177 # Return NULL
    tests:
      golang-lib-pq:
        - TestNullAfterNonNull

  - name: KIKIMR-18180 # Cancel process request by client command
    tests:
      golang-lib-pq:
        - TestQueryCancelRace

  - name: KIKIMR-18181 # Select generators
    tests:
      golang-lib-pq:
        - TestQueryCancelledReused

  - name: KIKIMR-17958  # Begin/Commit wire tags
    tests:
      golang-lib-pq:
        - TestQuickClose

  - name: KIKIMR-18186  # select current_setting
    tests:
      golang-lib-pq:
        - TestTxOptions

  - name: KIKIMR-18179  # Support rollback
    tests:
      golang-lib-pq:
        - TestPing

  - name: KIKIMR-18190  # DateRange type
    tests:
      python-psycopg2:
        - tests.test_types_extras.RangeCasterTestCase.test_adapt_date_range
        - tests.test_types_extras.RangeCasterTestCase.test_adapt_number_range
        - tests.test_types_extras.RangeCasterTestCase.test_adapt_numeric_range
        - tests.test_types_extras.RangeCasterTestCase.test_cast_date
        - tests.test_types_extras.RangeCasterTestCase.test_cast_empty
        - tests.test_types_extras.RangeCasterTestCase.test_cast_inf
        - tests.test_types_extras.RangeCasterTestCase.test_cast_null
        - tests.test_types_extras.RangeCasterTestCase.test_cast_numbers
        - tests.test_types_extras.RangeCasterTestCase.test_cast_timestamp
        - tests.test_types_extras.RangeCasterTestCase.test_cast_timestamptz

  - name: KIKIMR-18191  # Cannot find table 'db.[/local/pg_namespace]'
    tests:
      python-psycopg2:
        - tests.test_types_extras.RangeCasterTestCase.test_rang_weird_name

  - name: KIKIMR-18073  # Tables without primary key
    tests:
      python-psycopg2:
        - tests.test_psycopg2_dbapi20.Psycopg2Tests.test_None
        - tests.test_connection.SignalTestCase.test_bug_551_no_returning
        - tests.test_connection.SignalTestCase.test_bug_551_returning


  - name: KIKIMR-18275  # VariableSetStmt, not supported name
    tests:
      golang-lib-pq:
        - TestByteaOutputFormats
      python-psycopg2:
        - tests.test_connection.TransactionControlTests.test_idempotence_check
        - tests.test_connection.TransactionControlTests.test_mixing_session_attribs

  - name: KIKIMR-18276  # SHOW, unrecognized configuration parameter
    tests:
      python-psycopg2:
        - tests.test_psycopg2_dbapi20.Psycopg2TPCTests.test_commit_in_tpc_fails
        - tests.test_psycopg2_dbapi20.Psycopg2TPCTests.test_rollback_in_tpc_fails
        - tests.test_psycopg2_dbapi20.Psycopg2TPCTests.test_tpc_begin
        - tests.test_psycopg2_dbapi20.Psycopg2TPCTests.test_tpc_begin_in_tpc_transaction_fails
        - tests.test_psycopg2_dbapi20.Psycopg2TPCTests.test_tpc_begin_in_transaction_fails
        - tests.test_psycopg2_dbapi20.Psycopg2TPCTests.test_tpc_commit_with_prepare
        - tests.test_psycopg2_dbapi20.Psycopg2TPCTests.test_tpc_commit_without_prepare
        - tests.test_psycopg2_dbapi20.Psycopg2TPCTests.test_tpc_rollback_with_prepare
        - tests.test_psycopg2_dbapi20.Psycopg2TPCTests.test_tpc_rollback_without_prepare
        - tests.test_psycopg2_dbapi20.Psycopg2TPCTests.test_xid
        - tests.test_connection.TransactionControlTests.test_set_default
        - tests.test_connection.TransactionControlTests.test_set_deferrable
        - tests.test_connection.TransactionControlTests.test_set_isolation_level
        - tests.test_connection.TransactionControlTests.test_set_isolation_level_str
        - tests.test_connection.TransactionControlTests.test_set_read_only
        - tests.test_connection.TransactionControlTests.test_setattr_deferrable
        - tests.test_connection.TransactionControlTests.test_setattr_read_only

  - name: KIKIMR-18279 # DELETE without filter
    tests:
      python-psycopg2:
        - tests.test_with.WithConnectionTestCase.test_cant_reenter
        - tests.test_with.WithConnectionTestCase.test_subclass_commit
        - tests.test_with.WithConnectionTestCase.test_subclass_rollback
        - tests.test_with.WithConnectionTestCase.test_with_autocommit
        - tests.test_with.WithConnectionTestCase.test_with_autocommit_pgerror
        - tests.test_with.WithConnectionTestCase.test_with_autocommit_pyerror
        - tests.test_with.WithConnectionTestCase.test_with_closed
        - tests.test_with.WithConnectionTestCase.test_with_connect_idiom
        - tests.test_with.WithConnectionTestCase.test_with_error_db
        - tests.test_with.WithConnectionTestCase.test_with_error_python
        - tests.test_with.WithConnectionTestCase.test_with_ok
