convert:
  change_error_to_failure: True

tickets:
  - name:  KIKIMR-17960 # CREATE TEMP TABLE
    tests:
      golang-lib-pq:
        - TestBindError
        - TestCommit
        - TestCopyFromError
        - TestCopyInBinaryError
        - TestErrorDuringStartupClosesConn
        - TestCommit
        - TestCopyFromError
        - TestCopyInBinaryError
        - TestCopyInMultipleValues
        - TestCopyInStmtAffectedRows
        - TestCopyInTypes
        - TestCopyInWrongType
        - TestCopyRespLoopConnectionError
        - TestErrorOnExec
        - TestErrorOnQuery
        - TestErrorOnQueryRowSimpleQuery
        - TestExec
        - TestIssue494
        - TestQueryRowBugWorkaround
        - TestReturning
        - TestRowsResultTag

  - name: KIKIMR-18080 # Parameter types
    tests:
      golang-lib-pq:
        - TestArrayValueBackend

  - name: KIKIMR-18115 # PG error format
    tests:
      golang-lib-pq:
        - TestBinaryByteSliceToInt
        - TestBinaryByteSlicetoUUID
        - TestErrorClass

  - name: KIKIMR-18122 # PG error codes and text
    tests:
      golang-lib-pq:
        - TestCopySyntaxError

  - name: KIKIMR-18049 # Pg Auth error
    tests:
      golang-lib-pq:
        - TestErrorDuringStartup

  - name: KIKIMR-18050 # Pg exnexisted table error
    tests:
      golang-lib-pq:
        - TestIssue617

  - name: KIKIMR-18116 # Prepare description. expected syntax error, got pq: got 1 parameters but the statement requires 0
    tests:
      golang-lib-pq:
        - TestByteSliceToText
        - TestDecodeUUIDBackend
        - TestEmptyResultSetColumns
        - TestEncodeAndParseTs
        - TestEncodeDecode
        - TestFormatTsBackend
        - TestInfinityTimestamp
        - TestIssue186
        - TestIssue196
        - TestParseErrorInExtendedQuery
        - TestReconnect
        - TestRuntimeParameters
        - TestStringToBytea
        - TestStringToUUID
        - TestTextByteSliceToInt
        - TestTextByteSliceToUUID
        - TestTimeWithTimezone
        - TestTimeWithTimezone/11:59:59+00:00_=>_0000-01-01T11:59:59Z
        - TestTimeWithTimezone/11:59:59+04:00_=>_0000-01-01T11:59:59+04:00
        - TestTimeWithTimezone/11:59:59+04:01:02_=>_0000-01-01T11:59:59+04:01
        - TestTimeWithTimezone/11:59:59-04:01:02_=>_0000-01-01T11:59:59-04:01
        - TestTimeWithTimezone/24:00+00_=>_0000-01-02T00:00:00Z
        - TestTimeWithTimezone/24:00Z_=>_0000-01-02T00:00:00Z
        - TestTimeWithTimezone/24:00-04:00_=>_0000-01-02T00:00:00-04:00
        - TestTimeWithTimezone/24:00:00+00_=>_0000-01-02T00:00:00Z
        - TestTimeWithTimezone/24:00:00.0+00_=>_0000-01-02T00:00:00Z
        - TestTimeWithTimezone/24:00:00.000000+00_=>_0000-01-02T00:00:00Z
        - TestTimeWithoutTimezone
        - TestTimeWithoutTimezone/11:59:59_=>_0000-01-01T11:59:59Z
        - TestTimeWithoutTimezone/24:00_=>_0000-01-02T00:00:00Z
        - TestTimeWithoutTimezone/24:00:00_=>_0000-01-02T00:00:00Z
        - TestTimeWithoutTimezone/24:00:00.0_=>_0000-01-02T00:00:00Z
        - TestTimeWithoutTimezone/24:00:00.000000_=>_0000-01-02T00:00:00Z
        - TestTimestampWithOutTimezone

  - name: KIKIMR-18184  # Prepared queries
    tests:
      golang-lib-pq:
        - TestStatment

  - name: YQL-16021 # SHOW server_version_num, alternative is not implemented yet : 281
    tests:
      golang-lib-pq:
        - TestByteaOutputFormats
        - TestCopyInRaiseStmtTrigger
        - TestNotifyExtra

  - name: KIKIMR-18118 # Fail transaction on error
    tests:
      golang-lib-pq:
        - TestCommitInFailedTransaction
        - TestCommitInFailedTransactionWithCancelContext

  - name: KIKIMR-18119 # LISTEN Queries, alternative is not implemented yet : 267
    tests:
      golang-lib-pq:
        - TestConnListen
        - TestConnUnlisten
        - TestConnUnlistenAll
        - TestListenerFailedQuery
        - TestListenerListen
        - TestListenerReconnect
        - TestListenerUnlisten
        - TestListenerUnlistenAll

  - name: KIKIMR-18060 # SSL Response
    tests:
      golang-lib-pq:
        - TestConnectorWithNoticeHandler_Simple
        - TestConnectorWithNotificationHandler_Simple
        - TestNewConnector_Connect
        - TestNewConnector_Driver
        - TestNewConnector_WorksWithOpenDB

  - name: KIKIMR-18120 # implicit cast params (pg_sleep)
    tests:
      golang-lib-pq:
        - TestContextCancelBegin
        - TestContextCancelExec
        - TestContextCancelQuery
        - TestIssue1046
        - TestStmtExecContext
        - TestStmtExecContext/context.Background
        - TestStmtExecContext/context.WithTimeout_exceeded
        - TestStmtExecContext/context.WithTimeout
        - TestStmtQueryContext
        - TestStmtQueryContext/context.Background
        - TestStmtQueryContext/context.WithTimeout_exceeded
        - TestStmtQueryContext/context.WithTimeout

  - name: KIKIMR-18178 # SELECT USER. alternative is not implemented yet : 142
    tests:
      golang-lib-pq:
        - TestPgpass

  - name: KIKIMR-18125 # SET LOCAL search_path
    tests:
      golang-lib-pq:
        - TestIssue282

  - name: KIKIMR-18174 # SET time zone
    tests:
      golang-lib-pq:
        - TestMultipleSimpleQuery
        - TestTimestampWithTimeZone

  - name: KIKIMR-18059 # Multiply results
    tests:
      golang-lib-pq:
        - TestMultipleEmptyResult

  - name: KIKIMR-18147 # Information schema
    tests:
      golang-lib-pq:
        - TestMultipleResult

  - name: KIKIMR-18177 # Return NULL
    tests:
      golang-lib-pq:
        - TestNullAfterNonNull

  - name: KIKIMR-18180 # Cancel process request by client command
    tests:
      golang-lib-pq:
        - TestQueryCancelRace

  - name: KIKIMR-18181 # Select generators
    tests:
      golang-lib-pq:
        - TestQueryCancelledReused

  - name: KIKIMR-17958  # Begin/Commit wire tags
    tests:
      golang-lib-pq:
        - TestQuickClose

  - name: KIKIMR-18186  # select current_setting
    tests:
      golang-lib-pq:
        - TestTxOptions

  - name: KIKIMR-18179  # Support rollback
    tests:
      golang-lib-pq:
        - TestPing

