name: Tests

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '45 2 * * *'

env:
  TESTMO_URL: ${{ vars.TESTMO_URL }}
  TESTMO_PROJECT_ID: ${{ vars.TESTMO_PROJECT_ID }}
  TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}

jobs:
  test-init:
    runs-on: ubuntu-20.04
    outputs:
      testmo-run-id: ${{ steps.run-tests.outputs.testmo-run-id }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - run: |
          echo "Install testmo-cli"
          npm install -g @testmo/testmo-cli

      - run: |
          ./scripts/testmo-init-tests.bash
        id: run-tests

  test:
    needs: [test-init]
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        script:
          - ./languages/go/libpq/run-test.bash
          - ./languages/python/psycopg2/run-test.bash

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - run: scripts/install-tools.bash

      - run: bash "${{ matrix.script }}"

      - run: |
          echo "Upload results"
          scripts/prepare-junit-xml-report.py --unit-test-file-path=languages/go/libpq/unit-tests.txt --report-file-path=tmp/test-result/go-libpq/result.xml
          scripts/testmo-upload-results.bash

        env:
          TESTMO_RUN_ID: ${{ needs.test-init.outputs.testmo-run-id }}

  test-complete:
    runs-on: ubuntu-20.04
    needs: [test-init, test]
    if: always()
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - run: |
          scripts/install-tools.bash
          scripts/testmo-complete-tests.bash
        env:
          TESTMO_RUN_ID: ${{ needs.test-init.outputs.testmo-run-id }}
